# Generated by Django 4.2.29 on 2026-03-31 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            (
                                "story_parse",
                                "Story Parsing — extract fields from user story",
                            ),
                            ("narrative_gen", "Narrative Generation"),
                            ("rights_analysis", "Rights Violated Analysis"),
                            ("damages_gen", "Damages Section Generation"),
                            ("relief_gen", "Relief Sought Generation"),
                            ("court_lookup", "Federal Court Lookup Fallback"),
                            ("section_gen", "Generic Section Generation"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("system_prompt", models.TextField()),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Use {placeholders} for dynamic values injected at runtime"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(editable=False, max_length=20, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("paid", "Paid"),
                            ("finalized", "Finalized"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage Off"),
                            ("fixed", "Fixed Amount Off"),
                            ("free", "Free Access"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage (0-100) or fixed dollar amount",
                        max_digits=8,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WizardSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("analyzed", "Analyzed"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                (
                    "story_text",
                    models.TextField(
                        blank=True,
                        help_text="Raw story entered by user — AI parses this into fields",
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed AI output from story analysis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_session",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("contact_info", models.CharField(blank=True, max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What did this witness observe?"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReliefSought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monetary_damages", models.BooleanField(default=False)),
                ("injunctive_relief", models.BooleanField(default=False)),
                ("declaratory_relief", models.BooleanField(default=False)),
                ("attorney_fees", models.BooleanField(default=False)),
                (
                    "other_relief",
                    models.TextField(
                        blank=True, help_text="Any additional relief requested"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relief_sought",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriorComplaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filed_complaints",
                    models.BooleanField(
                        default=False,
                        help_text="Has the plaintiff previously filed complaints about this or related incidents?",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe prior complaints filed"
                    ),
                ),
                (
                    "outcomes",
                    models.TextField(blank=True, help_text="What were the outcomes?"),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prior_complaints",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prior Complaints",
            },
        ),
        migrations.CreateModel(
            name="PlaintiffInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaintiff_info",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateField(blank=True, null=True)),
                ("incident_time", models.TimeField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "federal_district_court",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "court_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="True once user has confirmed the court lookup result",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_overview",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "narrative",
                    models.TextField(
                        blank=True, help_text="Detailed description of what happened"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_narrative",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("medical_record", "Medical Record"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="evidence/"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evidence",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Defendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Officer, Detective, Warden",
                        max_length=255,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True,
                        help_text="e.g. NYPD, Rikers Island DOC",
                        max_length=255,
                    ),
                ),
                ("badge_number", models.CharField(blank=True, max_length=50)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defendants",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Damages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("physical_injuries", models.TextField(blank=True)),
                ("emotional_distress", models.TextField(blank=True)),
                ("financial_losses", models.TextField(blank=True)),
                ("other_damages", models.TextField(blank=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damages",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Damages",
            },
        ),
        migrations.CreateModel(
            name="RightsViolated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amendment",
                    models.CharField(
                        choices=[
                            (
                                "1st",
                                "First Amendment — Freedom of Speech, Religion, Assembly",
                            ),
                            (
                                "4th",
                                "Fourth Amendment — Unreasonable Search and Seizure",
                            ),
                            (
                                "5th",
                                "Fifth Amendment — Due Process / Self-Incrimination",
                            ),
                            ("6th", "Sixth Amendment — Right to Counsel / Fair Trial"),
                            ("8th", "Eighth Amendment — Cruel and Unusual Punishment"),
                            ("14th_due_process", "Fourteenth Amendment — Due Process"),
                            (
                                "14th_equal_protection",
                                "Fourteenth Amendment — Equal Protection",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detail about how this right was violated",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rights_violated",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "unique_together": {("document", "amendment")},
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_usages",
                        to="documents.document",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="documents.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_code_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("promo_code", "user")},
            },
        ),
    ]
