# Generated by Django 4.2.29 on 2026-03-31 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            (
                                "story_parse",
                                "Story Parsing — extract all fields from user story",
                            ),
                            (
                                "narrative_gen",
                                "Narrative / Factual Allegations Generation",
                            ),
                            ("claims_analysis", "Constitutional Claims Analysis"),
                            ("damages_gen", "Damages Section Generation"),
                            ("relief_gen", "Relief Sought Generation"),
                            ("court_lookup", "Federal Court Lookup Fallback"),
                            (
                                "monell_gen",
                                "Monell / Government Entity Section Generation",
                            ),
                            ("section_gen", "Generic Section Generation"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("system_prompt", models.TextField()),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Use {placeholders} for dynamic values injected at runtime"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(editable=False, max_length=20, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("paid", "Paid"),
                            ("finalized", "Finalized"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "jury_trial_demand",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include a jury trial demand in the complaint",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage Off"),
                            ("fixed", "Fixed Amount Off"),
                            ("free", "Free Access"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage (0-100) or fixed dollar amount",
                        max_digits=8,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WizardSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("analyzed", "Analyzed"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=0)),
                (
                    "story_text",
                    models.TextField(
                        blank=True,
                        help_text="Raw story entered or dictated by user — AI parses this to pre-fill all wizard steps",
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data extracted by AI from story_text — used to pre-fill wizard steps",
                    ),
                ),
                ("ai_extraction_attempted", models.BooleanField(default=False)),
                ("ai_extraction_succeeded", models.BooleanField(default=False)),
                ("ai_extraction_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_session",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("contact_info", models.CharField(blank=True, max_length=255)),
                (
                    "relationship_to_plaintiff",
                    models.CharField(
                        blank=True,
                        help_text="e.g. bystander, friend, fellow protestor, coworker",
                        max_length=255,
                    ),
                ),
                ("what_they_witnessed", models.TextField(blank=True)),
                (
                    "has_video",
                    models.BooleanField(
                        blank=True,
                        help_text="Did this witness capture video of the incident?",
                        null=True,
                    ),
                ),
                ("willing_to_testify", models.BooleanField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "time_approximate",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "approximately 2:30 PM" or "after the arrest"',
                        max_length=100,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True,
                        help_text='Who performed this action — defendant name, "officers", "plaintiff", etc.',
                        max_length=255,
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        help_text="What happened — one discrete event per entry"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReliefSought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compensatory_damages", models.BooleanField(default=False)),
                (
                    "compensatory_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("punitive_damages", models.BooleanField(default=False)),
                ("declaratory_judgment", models.BooleanField(default=False)),
                ("injunctive_relief", models.BooleanField(default=False)),
                ("attorney_fees", models.BooleanField(default=False)),
                ("costs_of_suit", models.BooleanField(default=False)),
                ("other_relief", models.TextField(blank=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relief_sought",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriorComplaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filed_complaints",
                    models.BooleanField(
                        default=False,
                        help_text="Has the plaintiff previously filed complaints about this or related incidents?",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("outcomes", models.TextField(blank=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prior_complaints",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prior Complaints",
            },
        ),
        migrations.CreateModel(
            name="PlaintiffInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "filing_pro_se",
                    models.BooleanField(
                        default=True, help_text="Filing without an attorney"
                    ),
                ),
                ("attorney_name", models.CharField(blank=True, max_length=255)),
                ("attorney_bar_number", models.CharField(blank=True, max_length=100)),
                ("attorney_address", models.CharField(blank=True, max_length=500)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaintiff_info",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateField(blank=True, null=True)),
                ("incident_time", models.TimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("location_description", models.TextField(blank=True)),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public_sidewalk", "Public Sidewalk"),
                            ("public_building", "Public Building"),
                            ("park", "Park"),
                            ("roadway", "Roadway"),
                            ("private_residence", "Private Residence"),
                            ("vehicle", "Vehicle"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "is_public_forum",
                    models.BooleanField(
                        blank=True,
                        help_text="Relevant to First Amendment forum analysis",
                        null=True,
                    ),
                ),
                (
                    "plaintiff_activity",
                    models.TextField(
                        blank=True,
                        help_text="What was the plaintiff doing at the time of the incident?",
                    ),
                ),
                (
                    "plaintiff_identified_themselves",
                    models.BooleanField(blank=True, null=True),
                ),
                ("identification_description", models.TextField(blank=True)),
                ("force_used", models.BooleanField(blank=True, null=True)),
                (
                    "equipment_seized_or_damaged",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "federal_district_court",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "court_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="True once user has confirmed the court lookup result",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_overview",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GovernmentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. City of Chicago, Los Angeles County Sheriff's Department",
                        max_length=255,
                    ),
                ),
                ("entity_address", models.CharField(blank=True, max_length=500)),
                (
                    "policy_or_custom_description",
                    models.TextField(
                        blank=True,
                        help_text="Describe the policy, custom, or practice that caused the violation",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="government_entity",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Government Entity (Monell)",
                "verbose_name_plural": "Government Entities (Monell)",
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("photo", "Photo"),
                            ("police_report", "Police Report"),
                            ("body_cam", "Body Camera Footage"),
                            ("foia_request", "FOIA Request / Response"),
                            ("citation", "Citation / Summons"),
                            ("medical_record", "Medical Record"),
                            ("physical", "Physical Evidence"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "date_and_time",
                    models.CharField(
                        blank=True,
                        help_text="Approximate date/time this evidence was created or captured",
                        max_length=100,
                    ),
                ),
                ("recorded_by", models.CharField(blank=True, max_length=255)),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Where is this evidence stored? e.g. phone, cloud, attorney office",
                        max_length=500,
                    ),
                ),
                (
                    "public_url",
                    models.URLField(
                        blank=True,
                        help_text="Public URL if evidence is accessible online (e.g. YouTube)",
                    ),
                ),
                (
                    "defendant_aware_of_recording",
                    models.BooleanField(
                        blank=True,
                        help_text="Relevant to First Amendment retaliation claims",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="evidence/"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evidence",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Defendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("badge_number", models.CharField(blank=True, max_length=50)),
                (
                    "rank_title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Officer, Detective, Sergeant, Warden",
                        max_length=255,
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. NYPD, Rikers Island DOC",
                        max_length=255,
                    ),
                ),
                (
                    "parent_government_entity",
                    models.CharField(
                        blank=True,
                        help_text="e.g. City of New York, Cook County",
                        max_length=255,
                    ),
                ),
                ("agency_address", models.CharField(blank=True, max_length=500)),
                (
                    "capacity_sued",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Capacity"),
                            ("official", "Official Capacity"),
                            ("both", "Both Individual and Official Capacity"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "acting_under_color_of_law",
                    models.BooleanField(
                        default=True,
                        help_text="The central element of a 1983 claim — defendant acted under state authority",
                    ),
                ),
                (
                    "color_of_law_basis",
                    models.TextField(
                        blank=True,
                        help_text="How this defendant was acting under color of law",
                    ),
                ),
                (
                    "is_supervisor",
                    models.BooleanField(
                        default=False,
                        help_text="Supervisor liability — knew of and failed to prevent subordinate violations",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defendants",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Damages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("physical_injury_description", models.TextField(blank=True)),
                ("emotional_distress_description", models.TextField(blank=True)),
                (
                    "lost_wages",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "property_damage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "punitive_basis",
                    models.TextField(
                        blank=True,
                        help_text="Basis for punitive damages — describe the malicious or reckless conduct",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damages",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Damages",
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_usages",
                        to="documents.document",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="documents.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_code_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("promo_code", "user")},
            },
        ),
        migrations.CreateModel(
            name="ConstitutionalClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amendment",
                    models.CharField(
                        choices=[
                            (
                                "1st",
                                "First Amendment — Freedom of Speech, Religion, Assembly, Press",
                            ),
                            (
                                "1st_retaliation",
                                "First Amendment — Retaliation for Protected Activity",
                            ),
                            (
                                "1st_prior_restraint",
                                "First Amendment — Prior Restraint",
                            ),
                            (
                                "1st_viewpoint",
                                "First Amendment — Viewpoint Discrimination",
                            ),
                            ("4th_search", "Fourth Amendment — Unreasonable Search"),
                            (
                                "4th_seizure",
                                "Fourth Amendment — Unreasonable Seizure of Person",
                            ),
                            (
                                "4th_property",
                                "Fourth Amendment — Unreasonable Seizure of Property",
                            ),
                            (
                                "4th_excessive_force",
                                "Fourth Amendment — Excessive Force",
                            ),
                            ("5th_due_process", "Fifth Amendment — Due Process"),
                            (
                                "5th_self_incrimination",
                                "Fifth Amendment — Self-Incrimination",
                            ),
                            ("6th_counsel", "Sixth Amendment — Right to Counsel"),
                            (
                                "8th_cruel",
                                "Eighth Amendment — Cruel and Unusual Punishment",
                            ),
                            ("14th_due_process", "Fourteenth Amendment — Due Process"),
                            (
                                "14th_equal_protection",
                                "Fourteenth Amendment — Equal Protection",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "how_violated",
                    models.TextField(
                        blank=True,
                        help_text="Describe specifically how this right was violated",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constitutional_claims",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "unique_together": {("document", "amendment")},
            },
        ),
    ]
