# Generated by Django 4.2.29 on 2026-03-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short label shown in the dropdown", max_length=200
                    ),
                ),
                (
                    "story_text",
                    models.TextField(
                        help_text="Full story text — loaded into the story textarea when selected"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Example Story",
                "verbose_name_plural": "Example Stories",
                "ordering": ["order", "title"],
            },
        ),
    ]
