# Generated by Django 4.2.29 on 2026-04-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_caselaw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselaw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
