from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_download_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='auto_grants_tester',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'When True, anyone who enters this code in the signup form is '
                    'automatically marked as is_tester=True (gets the example-stories '
                    'autofill + "Test mode" badge) AND the code is stashed in their '
                    'session so it pre-applies at checkout. Use this on the promo '
                    'codes generated by `seed_tester_promo` so testers only have to '
                    'enter one code to get the full test experience.'
                ),
            ),
        ),
    ]
