# Generated by Django 4.2.30 on 2026-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0023_testerfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentoverview",
            name="zip_code",
            field=models.CharField(
                blank=True,
                help_text="Incident ZIP — used to verify county for unincorporated areas the city/state lookup misses.",
                max_length=10,
            ),
        ),
    ]
