# Generated by Django 4.2.30 on 2026-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0024_incidentoverview_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partneradjustment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="partnershiprequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
