# Generated by Django 4.2.30 on 2026-07-21 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Saint Louis, MO" or "Missouri" or "National"',
                        max_length=255,
                    ),
                ),
                ("complaint_email", models.EmailField(max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Agencies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("agencies_reviewed", "Agencies Reviewed"),
                            ("info_collected", "Info Collected"),
                            ("drafted", "Drafted"),
                            ("sent", "Sent"),
                        ],
                        default="intake",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=0)),
                ("video_url", models.URLField(max_length=500)),
                (
                    "video_platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("rumble", "Rumble"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("video_title", models.CharField(blank=True, max_length=500)),
                ("video_channel_name", models.CharField(blank=True, max_length=255)),
                ("video_description", models.TextField(blank=True)),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw metadata fetched from the platform (title, description, channel, etc.)",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="Auto-caption transcript fetched via Supadata, when available.",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='AI-extracted structured data. Shape: {"agencies": [str], "location": str, "incident_date": str, "contacts": [str], "summary": str}.',
                    ),
                ),
                ("extraction_error", models.TextField(blank=True)),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("full_name", "Include my full name"),
                            ("first_name", "First name only"),
                            ("anonymous", "Anonymous / concerned citizen"),
                        ],
                        default="full_name",
                        max_length=20,
                    ),
                ),
                ("user_city", models.CharField(blank=True, max_length=100)),
                ("user_state", models.CharField(blank=True, max_length=100)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional — where the agency can reply. Left blank (and omitted from the email entirely) if privacy_level is anonymous.",
                        max_length=254,
                    ),
                ),
                (
                    "personal_note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text note injected into every draft so complaints vary person-to-person instead of reading like an identical form letter.",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("factual", "Factual / Neutral"),
                            ("firm", "Firm / Direct"),
                            ("concerned", "Concerned Citizen"),
                        ],
                        default="factual",
                        max_length=20,
                    ),
                ),
                (
                    "api_calls_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Counts every paid/external call this incident has triggered — transcript fetch, metadata fetch, GPT extraction, agency search, per-agency drafts.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TargetAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role_description",
                    models.CharField(
                        blank=True,
                        help_text='How this agency relates to the incident, e.g. "Venue — policy violation" or "Responding police department — unlawful detention". Tailors the draft.',
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("detected", "Detected from video"),
                            ("db_match", "Matched curated Agency DB"),
                            ("ai_lookup", "AI-assisted web lookup"),
                            ("manual", "Manually added by user"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="User has checked the send box and reviewed this recipient. Never auto-sent without this.",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_agencies",
                        to="citizen_complaint.incident",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Target agencies",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="AI-drafted, user-editable complaint email body.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set the first time the user opens this draft for review. Send is blocked until every selected draft has been viewed.",
                        null=True,
                    ),
                ),
                (
                    "recipient_email_snapshot",
                    models.EmailField(
                        blank=True,
                        help_text="Email address actually used at send time — kept even if TargetAgency.email is edited afterward, for an accurate audit trail.",
                        max_length=254,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="citizen_complaint.incident",
                    ),
                ),
                (
                    "target_agency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint",
                        to="citizen_complaint.targetagency",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
