# Generated by Django 4.2.30 on 2026-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen_complaint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="moderation_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="OpenAI moderation categories that were flagged, if any — for admin review.",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="moderation_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this body was last screened by the OpenAI Moderation API before send.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="moderation_flagged",
            field=models.BooleanField(
                default=False,
                help_text="True if the last moderation check blocked this from sending (threats/violence/harassment, or the check itself failed).",
            ),
        ),
    ]
